name: Deploy NextApp

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Download from GitHub
        run: git clone https://github.com/ankithaphilip/pearthoughttask1.git

      - name: Navigate to directory
        run: cd pearthoughttask1

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run start
