name: Deploy NestJS App

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Deploy to the instance
        env:
          SSH_USERNAME: ubuntu  # Replace with your SSH username
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -vvv -o StrictHostKeyChecking=no $SSH_USERNAME@your-server-ip "bash -s" <<'EOF'
            set -e
            echo "Checking if the directory /home/$SSH_USERNAME/typescript-starter exists..."
            if [ ! -d "/home/$SSH_USERNAME/typescript-starter" ]; then
              echo "Directory /home/$SSH_USERNAME/typescript-starter does not exist. Creating it..."
              mkdir -p /home/$SSH_USERNAME/typescript-starter
            fi
            cd /home/$SSH_USERNAME/typescript-starter
            echo "Directory contents:"
            ls -la
            npm install
            npm run build
            pm2 stop nestjs-hello-world || true
            pm2 start dist/main.js --name "nestjs-hello-world"
          EOF
